wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.0
    start_time: 1649891403
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 2
      4: 3.10.0
      5: 0.12.11
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 64
evo_dataset_for_novelty:
  desc: null
  value: cifar10
evo_gens:
  desc: null
  value: 100
evo_num_children:
  desc: null
  value: 50
evo_num_runs:
  desc: null
  value: 10
evo_num_winners:
  desc: null
  value: 2
evo_pop:
  desc: null
  value: 50
evo_tourney_size:
  desc: null
  value: 4
experiment_name:
  desc: null
  value: longer evolution
