#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ERDCV0089CDAG
#PBS -q standard
#PBS -l select=1:ncpus=44:mpiprocs=44
#PBS -l walltime=24:00:00
#PBS -l application=novel-feature-detector
#PBS -j oe

cd $WORK/rditljtd/Novel-Feature-Detector

module load $PROJECTS_HOME/datools/modulefiles/anaconda/3
source $HOME/.bashrc
conda activate EC2

wandb login --relogin e50cb709dc2bf04072661be1d9b46ec60d59e556
wandb online
ccmrun python evolution.py --evo_num_runs=10 --experiment_name="relative diversity k10 prms" --k=10 --pairwise_diversity_op='rms'
rsync -av --update /p/work/rditljtd/Novel-Feature-Detector/* /p/home/rditljtd/Novel-Feature-Detector/ --exclude wandb/ --exclude lightning_logs/