#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ERDCV0089CDAG
#PBS -q standard
#PBS -l select=1:ncpus=22:mpiprocs=2:ngpus=1
#PBS -l walltime=24:00:00
#PBS -l application=novel-feature-detector
#PBS -j oe


cd $WORK/rditljtd/Novel-Feature-Detector


module load $PROJECTS_HOME/datools/modulefiles/anaconda/3
source $HOME/.bashrc
conda activate EC2

ccmrun python train_and_eval.py --experiment_name="relative diversity k10 furthest" --fixed_conv